### ISSUE TITLE
Getting error when using newest version of Dynamic Bone Container

### ISSUE THREAD

**Issue by WillBillMG** [Dreadrith/PhysBone-Converter#1]
When I try to use Dynamic bone container the converter will not appear at the top tool bar and instead give an error that says the following: "the type or namespace name 'DynamicBonePlaneCollider' could not be found."

**Comment by Dreadrith** [comment]
Thank you for reporting.
It seems that the Markcreator didn't include the Plane Collider script in the package because VRC didn't use it. I've posted this as an issue on their Github. 

For now, you can likely manually fix this issue by making a new script called `DynamicBonePlaneCollider`, with only this line in it:
`public class DynamicBonePlaneCollider : DynamicBoneColliderBase {}`

**Comment by WillBillMG** [comment]
that worked thank you so much
